#!/bin/sh

for i in `seq 0 5`; do
    port="$((4200+$i))"

    shellinaboxd \
      --localhost-only \
      --background="./shellinabox.$i.pid" \
      --port=$port \
      --service /:james:staff:HOME:"env SSH_AUTH_SOCK=$SSH_AUTH_SOCK ssh -vv root@162.243.109.190 cd dcm" \
      --css white-on-black.css \
      --no-beep \
      --numeric \
      --disable-ssl
done
